# Generated by Django 4.2.11 on 2024-06-05 14:08

import base_app.models.user
import base_app.models.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', base_app.models.user.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='track',
            name='track',
            field=models.FileField(max_length=255, upload_to=base_app.models.utils.DynamicPath('users/{track.uploaded_by_id}/tracks/{track.uuid}', ext='.opus', name='track', pass_as='track'), validators=[base_app.models.utils.FileValidator(content_types={'audio/ogg', 'audio/mpeg', 'audio/x-aiff', 'audio/wav', 'audio/x-m4a', 'audio/flac'}, max_size=1073741824), django.core.validators.FileExtensionValidator({'flac', 'opus', 'alac', 'mp3', 'ogg', 'aiff', 'mp2', 'wav'}, 'Invalid audio format valid formats are: flac, opus, alac, mp3, ogg, aiff, mp2, wav')], verbose_name='Track file'),
        ),
    ]
